import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import ThemeProvider from "@/client/providers/theme-provider";
import { Toaster } from "@/client/components/ui/toaster";
import "./globals.css";

const font = Rubik({ weight: ["300", "400", "600"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={font.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
